### ISSUE TITLE
X help NEWPASS : please add the command syntax

### ISSUE THREAD

**Issue by man-d67** [IRC4Fun/GNUWorld-Issues#6]
Hello,

The X's help output for the NEWPASS command could be more complete and helpful.
How do we correctly use/type that command?
/msg x NEWPASS the_new_password or /msg x NEWPASS old_password new_password?
Thanks,

**Comment by man-d67** [comment]
Thank you!

**Comment by siniStar7** [comment]
I will add the SYNTAX to the help command for NEWPASS at the next update. :)

**Comment by siniStar7** [comment]
Apparently I had not updated X's language table for this, yet..  

However, it may not be applicable/necessary much longer as there are plans to _disable_ the **NEWPASS** command on X and **_require_** that password changes take place on the [Web Interface](https://cservice.irc4fun.net/live).

The reasons for this change _(coming soon)_ are:

- Easier for the user to change their password.
- Allows us to require **_stronger_** passwords _(by requiring letters + numbers + symbols)_

As soon as the **NEWPASS** command is disabled, I will close this issue. :)

**Comment by siniStar7** [comment]
The NEWPASS command syntax has been updated in X's HELP tables (live).  The NEWPASS command is still due to be disabled in the near future as we transition to password changes on the web interface only..  At that time, the HELP for NEWPASS will be updated again to reflect that.
